name: Fetch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch and commit
        run: |
          cd docker-nginx
          git pull
          cd ..
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com" 
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: fetch from upstream"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}